InApp message show callback
exponea/exponea-android-sdk pull request #72
Opened 2024-05-07 10:50 UTC by cernfr1993

feat: Added callback for InAppMessage displayed event.

2024-05-07 13:53 UTC, adam1929 requested changes

2024-05-07 13:53 UTC, adam1929 commented on sdk/src/main/java/com/exponea/sdk/Exponea.kt
> +    var inAppMessageCallback: InAppMessageCallback = Constants.InApps.defaultInAppMessageDelegate
please do not rename already published API - it will lead to compile errors

2024-05-07 13:53 UTC, adam1929 commented on sdk/src/main/java/com/exponea/sdk/manager/InAppMessageManagerImpl.kt
> +            runOnMainThread {
please trackShowEvent first, then invoke custom logging to prevent any error/exception to stop tracking

2024-05-07 13:53 UTC, adam1929 commented on sdk/src/main/java/com/exponea/sdk/manager/InAppMessageManagerImpl.kt
> +                            runOnMainThread {
please trackShowEvent first, then invoke custom logging to prevent any error/exception to stop tracking

2024-05-07 13:53 UTC, adam1929 commented on sdk/src/test/java/com/exponea/sdk/manager/InAppMessageManagerImplTest.kt
> +            override fun inAppMessageShow(message: InAppMessage) {}
please provide few unit tests, when it should be called and when not.
This is optional, but we are not aware of 'expectations'

2024-06-27 14:50 UTC, xcibik00 commented
Hi @cernfr1993 , its already available in version 3.15.0 as https://github.com/exponea/exponea-android-sdk/commit/c6f3cf415c79ef96ef846ef8d9f560423f0c333a

2024-06-27 14:50 UTC, closed without merging